Models
it-top-shambala/PersonalFinance pull request #1
Opened 2023-01-28 15:34 UTC by MishaHaritonenko

CREATE INDEX tab_currencies(
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    name TEXT,
    code TEXT,
    currency_id INTEGER
);

CREATE TABLE tab_wallets(
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    name TEXT,
    balance REAL,
    currency_id INTEGER,
    wallet_id INTEGER
);

CREATE TABLE tab_categories(
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    name TEXT,
    type BOOLEAN,
    category_id INTEGER
);

CREATE TABLE tab_wallets(
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    name TEXT,
    balance REAL,
    currency_id INTEGER,
    wallet_id INTEGER
);

CREATE TABLE tab_operations(
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    date_time TEXT,
    wallet_id INTEGER,
    category_id INTEGER,
    summa REAL,
    operation_id INTEGER
);

2023-01-30 07:59 UTC, nazardyumin commented on PersonalFinance.Lib/Models/Category.cs
> +        public int Category_id { get; set; }
Переименовать - CategoryId

2023-01-30 07:59 UTC, nazardyumin commented on PersonalFinance.Lib/Models/Operation.cs
> +        public int Operation_id { get; set; }
переименовать - OperationId

2023-01-30 08:00 UTC, nazardyumin commented on PersonalFinance.Lib/Models/Operation.cs
> +        public int Wallet_id { get; set; }
переименовать - WalletId

2023-01-30 08:00 UTC, nazardyumin commented on PersonalFinance.Lib/Models/Operation.cs
> +        public string? Name_category { get; set; }
переименовать - CategoryName

2023-01-30 08:01 UTC, nazardyumin commented on PersonalFinance.Lib/Models/Wallet.cs
> +        public int Wallet_id { get; set; }
переименовать - WalletId

2023-01-30 08:02 UTC, nazardyumin commented on PersonalFinance.Lib/Models/Currency.cs
> +        public int Currancy_id { get; set; }
переименовать - CurrencyId

2023-01-30 08:02 UTC, nazardyumin commented on PersonalFinance.Lib/Models/Wallet.cs
> +        public string? Name_currency { get; set; }
переименовать - CurrencyName

2023-01-30 08:03 UTC, nazardyumin requested changes
Переименуйте поля в соответствии с комментариями

2023-01-31 08:12 UTC, nazardyumin commented on PersonalFinance.Lib/Models/Currency.cs
> +        public int CurrancyId { get; set; }
CurrEEEEncyId))

2023-01-31 15:14 UTC, anst-foto commented on PersonalFinance.Lib/Models/Currency.cs
> +        public int CurrancyId { get; set; }
```suggestion
        public int CurrencyId { get; set; }
```

2023-02-01 05:46 UTC, nazardyumin approved these changes

2023-02-01 05:47 UTC, merged